seed: null
pretrained_model_name_or_path: stable-diffusion-v1-5/stable-diffusion-v1-5
instance_data_dir: ./data/dog
instance_prompt: a photo of sks dog
output_dir: checkpoints
logging_dir: logs
resolution: 512
with_prior_preservation: false
prior_loss_weight: 1.0
train_batch_size: 4
dataloader_num_workers: 0
gradient_accumulation_steps: 1
lora_rank: 4
learning_rate: 0.0005
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
lr_warmup_steps: 500
max_train_steps: null
num_train_epochs: 1
lr_scheduler: constant
lr_num_cycles: 1
lr_power: 1.0
max_grad_norm: 1.0
checkpointing_steps: 500
checkpoints_total_limit: null
validation_prompt: null
validation_epochs: 50
